#!/usr/bin/env python3
"""CLI for NocoDB MCP server.

Generated by: fastmcp generate-cli http://localhost:9876/mcp
"""

import json
import os
import sys
from typing import Annotated

import cyclopts
import mcp_types
from rich.console import Console

from fastmcp import Client
from fastmcp.client.transports import StdioTransport

# Modify this to change how the CLI connects to the MCP server.
CLIENT_SPEC = StdioTransport(
    command=sys.executable,
    args=["-m", "nocodb.mcpserver"],
    env=os.environ.copy(),
)

app = cyclopts.App(name="nocodb", help="NocoDB CLI - Agent-friendly command-line interface")
call_tool_app = cyclopts.App(name="call-tool", help="Call a tool on the server")
app.command(call_tool_app)

console = Console()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _print_tool_result(result):
    if result.is_error:
        for block in result.content:
            if isinstance(block, mcp_types.TextContent):
                console.print(f"[bold red]Error:[/bold red] {block.text}")
            else:
                console.print(f"[bold red]Error:[/bold red] {block}")
        sys.exit(1)

    if result.structured_content is not None:
        console.print_json(json.dumps(result.structured_content))
        return

    for block in result.content:
        if isinstance(block, mcp_types.TextContent):
            console.print(block.text)
        elif isinstance(block, mcp_types.ImageContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Image: {block.mime_type}, ~{size} bytes][/dim]")
        elif isinstance(block, mcp_types.AudioContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Audio: {block.mime_type}, ~{size} bytes][/dim]")


async def _call_tool(tool_name: str, arguments: dict) -> None:
    # Filter out None values and empty lists (defaults for optional array params)
    filtered = {
        k: v
        for k, v in arguments.items()
        if v is not None and (not isinstance(v, list) or len(v) > 0)
    }
    async with Client(CLIENT_SPEC) as client:
        result = await client.call_tool(tool_name, filtered, raise_on_error=False)
        _print_tool_result(result)
        if result.is_error:
            sys.exit(1)


# ---------------------------------------------------------------------------
# List / read commands
# ---------------------------------------------------------------------------


@app.command
async def list_tools() -> None:
    """List available tools."""
    async with Client(CLIENT_SPEC) as client:
        tools = await client.list_tools()
        if not tools:
            console.print("[dim]No tools found.[/dim]")
            return
        for tool in tools:
            sig_parts = []
            props = tool.input_schema.get("properties", {})
            required = set(tool.input_schema.get("required", []))
            for pname, pschema in props.items():
                ptype = pschema.get("type", "string")
                if pname in required:
                    sig_parts.append(f"{pname}: {ptype}")
                else:
                    sig_parts.append(f"{pname}: {ptype} = ...")
            sig = f"{tool.name}({', '.join(sig_parts)})"
            console.print(f"  [cyan]{sig}[/cyan]")
            if tool.description:
                console.print(f"    {tool.description}")
            console.print()


@app.command
async def list_resources() -> None:
    """List available resources."""
    async with Client(CLIENT_SPEC) as client:
        resources = await client.list_resources()
        if not resources:
            console.print("[dim]No resources found.[/dim]")
            return
        for r in resources:
            console.print(f"  [cyan]{r.uri}[/cyan]")
            desc_parts = [r.name or "", r.description or ""]
            desc = " — ".join(p for p in desc_parts if p)
            if desc:
                console.print(f"    {desc}")
        console.print()


@app.command
async def read_resource(uri: Annotated[str, cyclopts.Parameter(help="Resource URI")]) -> None:
    """Read a resource by URI."""
    async with Client(CLIENT_SPEC) as client:
        contents = await client.read_resource(uri)
        for block in contents:
            if isinstance(block, mcp_types.TextResourceContents):
                console.print(block.text)
            elif isinstance(block, mcp_types.BlobResourceContents):
                size = len(block.blob) * 3 // 4
                console.print(f"[dim][Blob: {block.mime_type}, ~{size} bytes][/dim]")


@app.command
async def list_prompts() -> None:
    """List available prompts."""
    async with Client(CLIENT_SPEC) as client:
        prompts = await client.list_prompts()
        if not prompts:
            console.print("[dim]No prompts found.[/dim]")
            return
        for p in prompts:
            args_str = ""
            if p.arguments:
                parts = [a.name for a in p.arguments]
                args_str = f"({', '.join(parts)})"
            console.print(f"  [cyan]{p.name}{args_str}[/cyan]")
            if p.description:
                console.print(f"    {p.description}")
        console.print()


@app.command
async def get_prompt(
    name: Annotated[str, cyclopts.Parameter(help="Prompt name")],
    *arguments: str,
) -> None:
    """Get a prompt by name. Pass arguments as key=value pairs."""
    parsed: dict[str, str] = {}
    for arg in arguments:
        if "=" not in arg:
            console.print(f"[bold red]Error:[/bold red] Invalid argument {arg!r} — expected key=value")
            sys.exit(1)
        key, value = arg.split("=", 1)
        parsed[key] = value

    async with Client(CLIENT_SPEC) as client:
        result = await client.get_prompt(name, parsed or None)
        for msg in result.messages:
            console.print(f"[bold]{msg.role}:[/bold]")
            if isinstance(msg.content, mcp_types.TextContent):
                console.print(f"  {msg.content.text}")
            elif isinstance(msg.content, mcp_types.ImageContent):
                size = len(msg.content.data) * 3 // 4
                console.print(f"  [dim][Image: {msg.content.mime_type}, ~{size} bytes][/dim]")
            else:
                console.print(f"  {msg.content}")
            console.print()


# ---------------------------------------------------------------------------
# Tool commands (generated from server schema)
# ---------------------------------------------------------------------------

@call_tool_app.command(name='records_list')
async def records_list(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
    fields: Annotated[str | None, cyclopts.Parameter(help="Comma-separated field names to include (e.g., \"Name,Email,Status\")\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Comma-separated field names to include (e.g., \\\"Name,Email,Status\\\")\"\n                          }")] = None,
    sort: Annotated[str | None, cyclopts.Parameter(help="Sort field(s), prefix with - for descending (e.g., \"-CreatedAt\" or \"Name,-Age\")\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Sort field(s), prefix with - for descending (e.g., \\\"-CreatedAt\\\" or \\\"Name,-Age\\\")\"\n                          }")] = None,
    where: Annotated[str | None, cyclopts.Parameter(help="Filter condition using NocoDB syntax (e.g., \"(Status,eq,Active)\")\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Filter condition using NocoDB syntax (e.g., \\\"(Status,eq,Active)\\\")\"\n                          }")] = None,
    page: Annotated[int, cyclopts.Parameter(help="Page number (1-indexed, default: 1)")] = 1,
    page_size: Annotated[int, cyclopts.Parameter(help="Records per page (default: 25, max: 1000)")] = 25,
    view_id: Annotated[str | None, cyclopts.Parameter(help="Optional view ID to filter by\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional view ID to filter by\"\n                          }")] = None,
) -> None:
    '''List records from a table with optional filtering and pagination.'''
    # Parse JSON parameters
    fields_parsed = json.loads(fields) if isinstance(fields, str) else fields
    sort_parsed = json.loads(sort) if isinstance(sort, str) else sort
    where_parsed = json.loads(where) if isinstance(where, str) else where
    view_id_parsed = json.loads(view_id) if isinstance(view_id, str) else view_id

    await _call_tool('records_list', {'table_id': table_id, 'fields': fields_parsed, 'sort': sort_parsed, 'where': where_parsed, 'page': page, 'page_size': page_size, 'view_id': view_id_parsed})


@call_tool_app.command(name='records_list_all')
async def records_list_all(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
    where: Annotated[str | None, cyclopts.Parameter(help="Optional filter condition\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional filter condition\"\n                          }")] = None,
    page_size: Annotated[int, cyclopts.Parameter(help="Records per page (default: 100)")] = 100,
    max_pages: Annotated[str | None, cyclopts.Parameter(help="Maximum pages to fetch (None = unlimited)\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"integer\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Maximum pages to fetch (None = unlimited)\"\n                          }")] = None,
) -> None:
    '''Fetch all records from a table, automatically handling pagination.

Use with caution on large tables. Consider using records_list with
pagination for better control.'''
    # Parse JSON parameters
    where_parsed = json.loads(where) if isinstance(where, str) else where
    max_pages_parsed = json.loads(max_pages) if isinstance(max_pages, str) else max_pages

    await _call_tool('records_list_all', {'table_id': table_id, 'where': where_parsed, 'page_size': page_size, 'max_pages': max_pages_parsed})


@call_tool_app.command(name='record_get')
async def record_get(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
    record_id: Annotated[str, cyclopts.Parameter(help="The record ID (e.g., \"1\" or \"rec_xxx\")")],
) -> None:
    '''Get a single record by ID.'''
    await _call_tool('record_get', {'table_id': table_id, 'record_id': record_id})


@call_tool_app.command(name='records_create')
async def records_create(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
    records: Annotated[str, cyclopts.Parameter(help="List of record data dicts. Each dict should contain field values.\nExample: [{\"Name\": \"John\", \"Email\": \"john@example.com\"}]\nFor batch: [{\"Name\": \"A\"}, {\"Name\": \"B\"}, {\"Name\": \"C\"}]\\nJSON Schema: {\n                            \"items\": {\n                              \"additionalProperties\": true,\n                              \"type\": \"object\"\n                            },\n                            \"type\": \"array\",\n                            \"description\": \"List of record data dicts. Each dict should contain field values.\\nExample: [{\\\"Name\\\": \\\"John\\\", \\\"Email\\\": \\\"john@example.com\\\"}]\\nFor batch: [{\\\"Name\\\": \\\"A\\\"}, {\\\"Name\\\": \\\"B\\\"}, {\\\"Name\\\": \\\"C\\\"}]\"\n                          }")],
) -> None:
    '''Create one or more records in a table.'''
    # Parse JSON parameters
    records_parsed = json.loads(records) if isinstance(records, str) else records

    await _call_tool('records_create', {'table_id': table_id, 'records': records_parsed})


@call_tool_app.command(name='records_update')
async def records_update(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
    records: Annotated[str, cyclopts.Parameter(help="List of record updates. Each dict must have \"id\" and field values.\nExample: [{\"id\": 1, \"Status\": \"Done\"}]\nFor batch: [{\"id\": 1, \"Status\": \"A\"}, {\"id\": 2, \"Status\": \"B\"}]\\nJSON Schema: {\n                            \"items\": {\n                              \"additionalProperties\": true,\n                              \"type\": \"object\"\n                            },\n                            \"type\": \"array\",\n                            \"description\": \"List of record updates. Each dict must have \\\"id\\\" and field values.\\nExample: [{\\\"id\\\": 1, \\\"Status\\\": \\\"Done\\\"}]\\nFor batch: [{\\\"id\\\": 1, \\\"Status\\\": \\\"A\\\"}, {\\\"id\\\": 2, \\\"Status\\\": \\\"B\\\"}]\"\n                          }")],
) -> None:
    '''Update one or more records in a table.'''
    # Parse JSON parameters
    records_parsed = json.loads(records) if isinstance(records, str) else records

    await _call_tool('records_update', {'table_id': table_id, 'records': records_parsed})


@call_tool_app.command(name='records_delete')
async def records_delete(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
    record_ids: Annotated[list[str], cyclopts.Parameter(help="List of record IDs to delete (e.g., [\"1\", \"2\", \"3\"])")],
    confirm: Annotated[bool, cyclopts.Parameter(help="Must be True to proceed with deletion")] = False,
) -> None:
    '''Delete one or more records from a table.

DESTRUCTIVE: This operation cannot be undone. Set confirm=True to proceed.'''
    await _call_tool('records_delete', {'table_id': table_id, 'record_ids': record_ids, 'confirm': confirm})


@call_tool_app.command(name='records_count')
async def records_count(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
    where: Annotated[str | None, cyclopts.Parameter(help="Optional filter condition (e.g., \"(Status,eq,Active)\")\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional filter condition (e.g., \\\"(Status,eq,Active)\\\")\"\n                          }")] = None,
) -> None:
    '''Count records in a table, optionally filtered.'''
    # Parse JSON parameters
    where_parsed = json.loads(where) if isinstance(where, str) else where

    await _call_tool('records_count', {'table_id': table_id, 'where': where_parsed})


@call_tool_app.command(name='bases_list')
async def bases_list(
) -> None:
    '''List all bases available to the current user.

Use this to discover base IDs for configuration.

Returns:
    BasesListResult with list of bases including id and title.

Note: The MCP server requires NOCODB_BASE_ID to be set.
This tool helps you find available base IDs if you need
to configure a different base.'''
    await _call_tool('bases_list', {})


@call_tool_app.command(name='base_info')
async def base_info(
) -> None:
    '''Get detailed information about the currently configured base.

Returns the base metadata including title and list of tables.

Returns:
    BaseInfoResult with base id, title, tables, and metadata.'''
    await _call_tool('base_info', {})


@call_tool_app.command(name='tables_list')
async def tables_list(
) -> None:
    '''List all tables in the current base.

Returns:
    TablesListResult with list of tables including id, title, and type.'''
    await _call_tool('tables_list', {})


@call_tool_app.command(name='table_get')
async def table_get(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
) -> None:
    '''Get detailed information about a table including its fields.'''
    await _call_tool('table_get', {'table_id': table_id})


@call_tool_app.command(name='table_create')
async def table_create(
    *,
    title: Annotated[str, cyclopts.Parameter(help="The table title (e.g., \"Users\", \"Tasks\")")],
    fields: Annotated[str | None, cyclopts.Parameter(help="Optional list of field definitions to create with the table.\nEach field should have \"title\" and \"type\" keys.\nExample: [{\"title\": \"Name\", \"type\": \"SingleLineText\"}, {\"title\": \"Email\", \"type\": \"Email\"}]\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"items\": {\n                                  \"additionalProperties\": true,\n                                  \"type\": \"object\"\n                                },\n                                \"type\": \"array\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional list of field definitions to create with the table.\\nEach field should have \\\"title\\\" and \\\"type\\\" keys.\\nExample: [{\\\"title\\\": \\\"Name\\\", \\\"type\\\": \\\"SingleLineText\\\"}, {\\\"title\\\": \\\"Email\\\", \\\"type\\\": \\\"Email\\\"}]\"\n                          }")] = None,
) -> None:
    '''Create a new table in the current base.'''
    # Parse JSON parameters
    fields_parsed = json.loads(fields) if isinstance(fields, str) else fields

    await _call_tool('table_create', {'title': title, 'fields': fields_parsed})


@call_tool_app.command(name='table_update')
async def table_update(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
    title: Annotated[str | None, cyclopts.Parameter(help="New table title\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"New table title\"\n                          }")] = None,
    icon: Annotated[str | None, cyclopts.Parameter(help="Table icon (emoji, e.g., \"🎯\")\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Table icon (emoji, e.g., \\\"🎯\\\")\"\n                          }")] = None,
    meta: Annotated[str | None, cyclopts.Parameter(help="Additional metadata dict\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"additionalProperties\": true,\n                                \"type\": \"object\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Additional metadata dict\"\n                          }")] = None,
) -> None:
    '''Update a table\'s metadata.'''
    # Parse JSON parameters
    title_parsed = json.loads(title) if isinstance(title, str) else title
    icon_parsed = json.loads(icon) if isinstance(icon, str) else icon
    meta_parsed = json.loads(meta) if isinstance(meta, str) else meta

    await _call_tool('table_update', {'table_id': table_id, 'title': title_parsed, 'icon': icon_parsed, 'meta': meta_parsed})


@call_tool_app.command(name='table_delete')
async def table_delete(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
    confirm: Annotated[bool, cyclopts.Parameter(help="Must be True to proceed with deletion")] = False,
) -> None:
    '''Delete a table and all its data.

DESTRUCTIVE: This permanently deletes the table, all its fields,
and ALL RECORDS. This cannot be undone. Set confirm=True to proceed.'''
    await _call_tool('table_delete', {'table_id': table_id, 'confirm': confirm})


@call_tool_app.command(name='fields_list')
async def fields_list(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
) -> None:
    '''List all fields in a table.'''
    await _call_tool('fields_list', {'table_id': table_id})


@call_tool_app.command(name='field_get')
async def field_get(
    *,
    field_id: Annotated[str, cyclopts.Parameter(help="The field ID (e.g., \"fld_xxx\")")],
) -> None:
    '''Get detailed information about a field.'''
    await _call_tool('field_get', {'field_id': field_id})


@call_tool_app.command(name='field_create')
async def field_create(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
    title: Annotated[str, cyclopts.Parameter(help="The field title (e.g., \"Status\", \"Email\")")],
    field_type: Annotated[str, cyclopts.Parameter(help="The field type (see list below)")],
    options: Annotated[str | None, cyclopts.Parameter(help="Optional field-specific options\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"additionalProperties\": true,\n                                \"type\": \"object\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional field-specific options\"\n                          }")] = None,
) -> None:
    '''Create a new field in a table.'''
    # Parse JSON parameters
    options_parsed = json.loads(options) if isinstance(options, str) else options

    await _call_tool('field_create', {'table_id': table_id, 'title': title, 'field_type': field_type, 'options': options_parsed})


@call_tool_app.command(name='field_update')
async def field_update(
    *,
    field_id: Annotated[str, cyclopts.Parameter(help="The field ID (e.g., \"fld_xxx\")")],
    title: Annotated[str | None, cyclopts.Parameter(help="New field title\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"New field title\"\n                          }")] = None,
    options: Annotated[str | None, cyclopts.Parameter(help="New field options (not for colOptions updates)\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"additionalProperties\": true,\n                                \"type\": \"object\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"New field options (not for colOptions updates)\"\n                          }")] = None,
) -> None:
    '''Update a field\'s metadata.

Note: For updating SingleSelect/MultiSelect colors, use field_update_options instead.'''
    # Parse JSON parameters
    title_parsed = json.loads(title) if isinstance(title, str) else title
    options_parsed = json.loads(options) if isinstance(options, str) else options

    await _call_tool('field_update', {'field_id': field_id, 'title': title_parsed, 'options': options_parsed})


@call_tool_app.command(name='field_update_options')
async def field_update_options(
    *,
    field_id: Annotated[str, cyclopts.Parameter(help="The field ID (e.g., \"fld_xxx\")")],
    col_options: Annotated[str, cyclopts.Parameter(help="The colOptions dict with updated choices.\nExample for SingleSelect colors:\n{\n    \"options\": [\n        {\"id\": \"opt_xxx\", \"title\": \"Active\", \"color\": \"#00FF00\"},\n        {\"id\": \"opt_yyy\", \"title\": \"Inactive\", \"color\": \"#FF0000\"}\n    ]\n}\\nJSON Schema: {\n                            \"additionalProperties\": true,\n                            \"type\": \"object\",\n                            \"description\": \"The colOptions dict with updated choices.\\nExample for SingleSelect colors:\\n{\\n    \\\"options\\\": [\\n        {\\\"id\\\": \\\"opt_xxx\\\", \\\"title\\\": \\\"Active\\\", \\\"color\\\": \\\"#00FF00\\\"},\\n        {\\\"id\\\": \\\"opt_yyy\\\", \\\"title\\\": \\\"Inactive\\\", \\\"color\\\": \\\"#FF0000\\\"}\\n    ]\\n}\"\n                          }")],
) -> None:
    '''Update a field\'s colOptions using v2 API.

Use this specifically for updating SingleSelect/MultiSelect choice colors,
which requires the v2 column update API.'''
    # Parse JSON parameters
    col_options_parsed = json.loads(col_options) if isinstance(col_options, str) else col_options

    await _call_tool('field_update_options', {'field_id': field_id, 'col_options': col_options_parsed})


@call_tool_app.command(name='field_delete')
async def field_delete(
    *,
    field_id: Annotated[str, cyclopts.Parameter(help="The field ID (e.g., \"fld_xxx\")")],
    confirm: Annotated[bool, cyclopts.Parameter(help="Must be True to proceed with deletion")] = False,
) -> None:
    '''Delete a field from a table.

DESTRUCTIVE: This permanently deletes the field and ALL DATA in that field
across all records. This cannot be undone. Set confirm=True to proceed.'''
    await _call_tool('field_delete', {'field_id': field_id, 'confirm': confirm})


@call_tool_app.command(name='linked_records_list')
async def linked_records_list(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID containing the link field (e.g., \"tbl_xxx\")")],
    link_field_id: Annotated[str, cyclopts.Parameter(help="The Links field ID (e.g., \"fld_xxx\")")],
    record_id: Annotated[str, cyclopts.Parameter(help="The record ID to get linked records for")],
    fields: Annotated[str | None, cyclopts.Parameter(help="Comma-separated field names to include from linked records\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Comma-separated field names to include from linked records\"\n                          }")] = None,
    sort: Annotated[str | None, cyclopts.Parameter(help="Sort field(s), prefix with - for descending\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Sort field(s), prefix with - for descending\"\n                          }")] = None,
    where: Annotated[str | None, cyclopts.Parameter(help="Filter condition for linked records\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Filter condition for linked records\"\n                          }")] = None,
) -> None:
    '''List records linked to a specific record via a Links field.'''
    # Parse JSON parameters
    fields_parsed = json.loads(fields) if isinstance(fields, str) else fields
    sort_parsed = json.loads(sort) if isinstance(sort, str) else sort
    where_parsed = json.loads(where) if isinstance(where, str) else where

    await _call_tool('linked_records_list', {'table_id': table_id, 'link_field_id': link_field_id, 'record_id': record_id, 'fields': fields_parsed, 'sort': sort_parsed, 'where': where_parsed})


@call_tool_app.command(name='linked_records_link')
async def linked_records_link(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID containing the link field (e.g., \"tbl_xxx\")")],
    link_field_id: Annotated[str, cyclopts.Parameter(help="The Links field ID (e.g., \"fld_xxx\")")],
    record_id: Annotated[str, cyclopts.Parameter(help="The source record ID to link from")],
    target_ids: Annotated[list[str], cyclopts.Parameter(help="List of record IDs to link to (e.g., [\"1\", \"2\", \"3\"])")],
) -> None:
    '''Link records together via a Links field.

Creates a relationship between the source record and target records.'''
    await _call_tool('linked_records_link', {'table_id': table_id, 'link_field_id': link_field_id, 'record_id': record_id, 'target_ids': target_ids})


@call_tool_app.command(name='linked_records_unlink')
async def linked_records_unlink(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID containing the link field (e.g., \"tbl_xxx\")")],
    link_field_id: Annotated[str, cyclopts.Parameter(help="The Links field ID (e.g., \"fld_xxx\")")],
    record_id: Annotated[str, cyclopts.Parameter(help="The source record ID to unlink from")],
    target_ids: Annotated[list[str], cyclopts.Parameter(help="List of record IDs to unlink (e.g., [\"1\", \"2\"])")],
    confirm: Annotated[bool, cyclopts.Parameter(help="Must be True to proceed with unlinking")] = False,
) -> None:
    '''Unlink records from a Links field relationship.

Removes the relationship between records. Does NOT delete the records themselves.

DESTRUCTIVE: Set confirm=True to proceed.'''
    await _call_tool('linked_records_unlink', {'table_id': table_id, 'link_field_id': link_field_id, 'record_id': record_id, 'target_ids': target_ids, 'confirm': confirm})


@call_tool_app.command(name='views_list')
async def views_list(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
) -> None:
    '''List all views for a table.

Views include Grid, Gallery, Form, Kanban, and Calendar views.'''
    await _call_tool('views_list', {'table_id': table_id})


@call_tool_app.command(name='view_update')
async def view_update(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
    title: Annotated[str | None, cyclopts.Parameter(help="New view title\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"New view title\"\n                          }")] = None,
    icon: Annotated[str | None, cyclopts.Parameter(help="View icon (emoji, e.g., \"📊\")\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"View icon (emoji, e.g., \\\"📊\\\")\"\n                          }")] = None,
    meta: Annotated[str | None, cyclopts.Parameter(help="Additional metadata dict\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"additionalProperties\": true,\n                                \"type\": \"object\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Additional metadata dict\"\n                          }")] = None,
) -> None:
    '''Update a view\'s metadata.'''
    # Parse JSON parameters
    title_parsed = json.loads(title) if isinstance(title, str) else title
    icon_parsed = json.loads(icon) if isinstance(icon, str) else icon
    meta_parsed = json.loads(meta) if isinstance(meta, str) else meta

    await _call_tool('view_update', {'view_id': view_id, 'title': title_parsed, 'icon': icon_parsed, 'meta': meta_parsed})


@call_tool_app.command(name='view_delete')
async def view_delete(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
    confirm: Annotated[bool, cyclopts.Parameter(help="Must be True to proceed with deletion")] = False,
) -> None:
    '''Delete a view.

This only deletes the view, not the underlying data.
Records remain intact.'''
    await _call_tool('view_delete', {'view_id': view_id, 'confirm': confirm})


@call_tool_app.command(name='view_filters_list')
async def view_filters_list(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
) -> None:
    '''List all filters for a view.'''
    await _call_tool('view_filters_list', {'view_id': view_id})


@call_tool_app.command(name='view_filter_get')
async def view_filter_get(
    *,
    filter_id: Annotated[str, cyclopts.Parameter(help="The filter ID (e.g., \"flt_xxx\")")],
) -> None:
    '''Get details of a single filter.'''
    await _call_tool('view_filter_get', {'filter_id': filter_id})


@call_tool_app.command(name='view_filter_create')
async def view_filter_create(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
    fk_column_id: Annotated[str, cyclopts.Parameter(help="The column/field ID to filter on (e.g., \"fld_xxx\")")],
    comparison_op: Annotated[str, cyclopts.Parameter(help="The comparison operator")],
    value: Annotated[str | None, cyclopts.Parameter(help="The filter value (not needed for null/empty checks)\\nJSON Schema: {\n                            \"default\": null,\n                            \"title\": \"Value\",\n                            \"description\": \"The filter value (not needed for null/empty checks)\"\n                          }")] = None,
) -> None:
    '''Create a new filter for a view.'''
    # Parse JSON parameters
    value_parsed = json.loads(value) if isinstance(value, str) else value

    await _call_tool('view_filter_create', {'view_id': view_id, 'fk_column_id': fk_column_id, 'comparison_op': comparison_op, 'value': value_parsed})


@call_tool_app.command(name='view_filter_update')
async def view_filter_update(
    *,
    filter_id: Annotated[str, cyclopts.Parameter(help="The filter ID (e.g., \"flt_xxx\")")],
    fk_column_id: Annotated[str | None, cyclopts.Parameter(help="New column/field ID\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"New column/field ID\"\n                          }")] = None,
    comparison_op: Annotated[str | None, cyclopts.Parameter(help="New comparison operator\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"New comparison operator\"\n                          }")] = None,
    value: Annotated[str | None, cyclopts.Parameter(help="New filter value\\nJSON Schema: {\n                            \"default\": null,\n                            \"title\": \"Value\",\n                            \"description\": \"New filter value\"\n                          }")] = None,
) -> None:
    '''Update an existing filter.'''
    # Parse JSON parameters
    fk_column_id_parsed = json.loads(fk_column_id) if isinstance(fk_column_id, str) else fk_column_id
    comparison_op_parsed = json.loads(comparison_op) if isinstance(comparison_op, str) else comparison_op
    value_parsed = json.loads(value) if isinstance(value, str) else value

    await _call_tool('view_filter_update', {'filter_id': filter_id, 'fk_column_id': fk_column_id_parsed, 'comparison_op': comparison_op_parsed, 'value': value_parsed})


@call_tool_app.command(name='view_filter_delete')
async def view_filter_delete(
    *,
    filter_id: Annotated[str, cyclopts.Parameter(help="The filter ID (e.g., \"flt_xxx\")")],
    confirm: Annotated[bool, cyclopts.Parameter(help="Must be True to proceed with deletion")] = False,
) -> None:
    '''Delete a filter from a view.'''
    await _call_tool('view_filter_delete', {'filter_id': filter_id, 'confirm': confirm})


@call_tool_app.command(name='view_filter_children')
async def view_filter_children(
    *,
    filter_group_id: Annotated[str, cyclopts.Parameter(help="The parent filter group ID")],
) -> None:
    '''Get children filters of a filter group.

Filter groups allow nested AND/OR logic.'''
    await _call_tool('view_filter_children', {'filter_group_id': filter_group_id})


@call_tool_app.command(name='view_sorts_list')
async def view_sorts_list(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
) -> None:
    '''List all sorts for a view.'''
    await _call_tool('view_sorts_list', {'view_id': view_id})


@call_tool_app.command(name='view_sort_get')
async def view_sort_get(
    *,
    sort_id: Annotated[str, cyclopts.Parameter(help="The sort ID (e.g., \"srt_xxx\")")],
) -> None:
    '''Get details of a single sort.'''
    await _call_tool('view_sort_get', {'sort_id': sort_id})


@call_tool_app.command(name='view_sort_create')
async def view_sort_create(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
    fk_column_id: Annotated[str, cyclopts.Parameter(help="The column/field ID to sort by (e.g., \"fld_xxx\")")],
    direction: Annotated[str, cyclopts.Parameter(help="Sort direction - \"asc\" (ascending) or \"desc\" (descending)")] = 'asc',
) -> None:
    '''Create a new sort for a view.'''
    await _call_tool('view_sort_create', {'view_id': view_id, 'fk_column_id': fk_column_id, 'direction': direction})


@call_tool_app.command(name='view_sort_update')
async def view_sort_update(
    *,
    sort_id: Annotated[str, cyclopts.Parameter(help="The sort ID (e.g., \"srt_xxx\")")],
    fk_column_id: Annotated[str | None, cyclopts.Parameter(help="New column/field ID\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"New column/field ID\"\n                          }")] = None,
    direction: Annotated[str | None, cyclopts.Parameter(help="New sort direction - \"asc\" or \"desc\"\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"New sort direction - \\\"asc\\\" or \\\"desc\\\"\"\n                          }")] = None,
) -> None:
    '''Update an existing sort.'''
    # Parse JSON parameters
    fk_column_id_parsed = json.loads(fk_column_id) if isinstance(fk_column_id, str) else fk_column_id
    direction_parsed = json.loads(direction) if isinstance(direction, str) else direction

    await _call_tool('view_sort_update', {'sort_id': sort_id, 'fk_column_id': fk_column_id_parsed, 'direction': direction_parsed})


@call_tool_app.command(name='view_sort_delete')
async def view_sort_delete(
    *,
    sort_id: Annotated[str, cyclopts.Parameter(help="The sort ID (e.g., \"srt_xxx\")")],
    confirm: Annotated[bool, cyclopts.Parameter(help="Must be True to proceed with deletion")] = False,
) -> None:
    '''Delete a sort from a view.'''
    await _call_tool('view_sort_delete', {'sort_id': sort_id, 'confirm': confirm})


@call_tool_app.command(name='view_columns_list')
async def view_columns_list(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
) -> None:
    '''List all columns in a view with their visibility settings.'''
    await _call_tool('view_columns_list', {'view_id': view_id})


@call_tool_app.command(name='view_column_update')
async def view_column_update(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
    column_id: Annotated[str, cyclopts.Parameter(help="The view column ID (from view_columns_list, not the field ID)")],
    show: Annotated[str | None, cyclopts.Parameter(help="Whether to show (True) or hide (False) the column\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"boolean\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Whether to show (True) or hide (False) the column\"\n                          }")] = None,
    order: Annotated[str | None, cyclopts.Parameter(help="Column position (0-indexed)\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"integer\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Column position (0-indexed)\"\n                          }")] = None,
) -> None:
    '''Update a column\'s visibility or order in a view.'''
    # Parse JSON parameters
    show_parsed = json.loads(show) if isinstance(show, str) else show
    order_parsed = json.loads(order) if isinstance(order, str) else order

    await _call_tool('view_column_update', {'view_id': view_id, 'column_id': column_id, 'show': show_parsed, 'order': order_parsed})


@call_tool_app.command(name='view_columns_hide_all')
async def view_columns_hide_all(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
) -> None:
    '''Hide all columns in a view.

Useful for starting fresh and then selectively showing specific columns.'''
    await _call_tool('view_columns_hide_all', {'view_id': view_id})


@call_tool_app.command(name='view_columns_show_all')
async def view_columns_show_all(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
) -> None:
    '''Show all columns in a view.'''
    await _call_tool('view_columns_show_all', {'view_id': view_id})


@call_tool_app.command(name='shared_views_list')
async def shared_views_list(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
) -> None:
    '''List all shared (public) views for a table.'''
    await _call_tool('shared_views_list', {'table_id': table_id})


@call_tool_app.command(name='shared_view_create')
async def shared_view_create(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
    password: Annotated[str | None, cyclopts.Parameter(help="Optional password to protect the shared view\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional password to protect the shared view\"\n                          }")] = None,
) -> None:
    '''Create a public link for a view.

This makes the view accessible via a unique URL without authentication.'''
    # Parse JSON parameters
    password_parsed = json.loads(password) if isinstance(password, str) else password

    await _call_tool('shared_view_create', {'view_id': view_id, 'password': password_parsed})


@call_tool_app.command(name='shared_view_update')
async def shared_view_update(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
    password: Annotated[str | None, cyclopts.Parameter(help="New password (or None to remove password protection)\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"New password (or None to remove password protection)\"\n                          }")] = None,
) -> None:
    '''Update a shared view\'s settings.'''
    # Parse JSON parameters
    password_parsed = json.loads(password) if isinstance(password, str) else password

    await _call_tool('shared_view_update', {'view_id': view_id, 'password': password_parsed})


@call_tool_app.command(name='shared_view_delete')
async def shared_view_delete(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
    confirm: Annotated[bool, cyclopts.Parameter(help="Must be True to proceed with removal")] = False,
) -> None:
    '''Remove public access from a view.

The public link will no longer work. The view itself is not deleted.'''
    await _call_tool('shared_view_delete', {'view_id': view_id, 'confirm': confirm})


@call_tool_app.command(name='webhooks_list')
async def webhooks_list(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
) -> None:
    '''List all webhooks for a table.'''
    await _call_tool('webhooks_list', {'table_id': table_id})


@call_tool_app.command(name='webhook_delete')
async def webhook_delete(
    *,
    hook_id: Annotated[str, cyclopts.Parameter(help="The webhook ID (e.g., \"hk_xxx\")")],
    confirm: Annotated[bool, cyclopts.Parameter(help="Must be True to proceed with deletion")] = False,
) -> None:
    '''Delete a webhook.'''
    await _call_tool('webhook_delete', {'hook_id': hook_id, 'confirm': confirm})


@call_tool_app.command(name='webhook_logs')
async def webhook_logs(
    *,
    hook_id: Annotated[str, cyclopts.Parameter(help="The webhook ID (e.g., \"hk_xxx\")")],
) -> None:
    '''View execution logs for a webhook.

Useful for debugging webhook delivery issues.'''
    await _call_tool('webhook_logs', {'hook_id': hook_id})


@call_tool_app.command(name='webhook_sample_payload')
async def webhook_sample_payload(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
    event: Annotated[str, cyclopts.Parameter(help="Event type - \"records\" (most common)")] = 'records',
    operation: Annotated[str, cyclopts.Parameter(help="Operation type - \"insert\", \"update\", \"delete\"")] = 'insert',
    version: Annotated[str, cyclopts.Parameter(help="Payload version - \"v1\" or \"v2\" (default: \"v2\")")] = 'v2',
) -> None:
    '''Get a sample webhook payload for testing.'''
    await _call_tool('webhook_sample_payload', {'table_id': table_id, 'event': event, 'operation': operation, 'version': version})


@call_tool_app.command(name='webhook_filters_list')
async def webhook_filters_list(
    *,
    hook_id: Annotated[str, cyclopts.Parameter(help="The webhook ID (e.g., \"hk_xxx\")")],
) -> None:
    '''List filters for a webhook.

Webhook filters determine when the webhook triggers based on field values.'''
    await _call_tool('webhook_filters_list', {'hook_id': hook_id})


@call_tool_app.command(name='webhook_filter_create')
async def webhook_filter_create(
    *,
    hook_id: Annotated[str, cyclopts.Parameter(help="The webhook ID (e.g., \"hk_xxx\")")],
    fk_column_id: Annotated[str, cyclopts.Parameter(help="The column/field ID to filter on")],
    comparison_op: Annotated[str, cyclopts.Parameter(help="The comparison operator (eq, neq, like, etc.)")],
    value: Annotated[str | None, cyclopts.Parameter(help="The filter value\\nJSON Schema: {\n                            \"default\": null,\n                            \"title\": \"Value\",\n                            \"description\": \"The filter value\"\n                          }")] = None,
) -> None:
    '''Create a filter for a webhook.

Filters control when the webhook fires based on field values.'''
    # Parse JSON parameters
    value_parsed = json.loads(value) if isinstance(value, str) else value

    await _call_tool('webhook_filter_create', {'hook_id': hook_id, 'fk_column_id': fk_column_id, 'comparison_op': comparison_op, 'value': value_parsed})


@call_tool_app.command(name='members_list')
async def members_list(
) -> None:
    '''List all members of the current base.

Returns:
    MembersListResult with list of members including id, email, and roles.'''
    await _call_tool('members_list', {})


@call_tool_app.command(name='member_add')
async def member_add(
    *,
    email: Annotated[str, cyclopts.Parameter(help="The user's email address")],
    role: Annotated[str, cyclopts.Parameter(help="The role to assign. Options:\n- owner: Full control\n- creator: Can create tables\n- editor: Can edit records\n- commenter: Can comment only\n- viewer: Read-only access")] = 'editor',
) -> None:
    '''Add a new member to the current base.'''
    await _call_tool('member_add', {'email': email, 'role': role})


@call_tool_app.command(name='member_update')
async def member_update(
    *,
    member_id: Annotated[str, cyclopts.Parameter(help="The member ID")],
    role: Annotated[str, cyclopts.Parameter(help="The new role. Options:\n- owner: Full control\n- creator: Can create tables\n- editor: Can edit records\n- commenter: Can comment only\n- viewer: Read-only access")],
) -> None:
    '''Update a member\'s role.'''
    await _call_tool('member_update', {'member_id': member_id, 'role': role})


@call_tool_app.command(name='member_remove')
async def member_remove(
    *,
    member_id: Annotated[str, cyclopts.Parameter(help="The member ID to remove")],
    confirm: Annotated[bool, cyclopts.Parameter(help="Must be True to proceed with removal")] = False,
) -> None:
    '''Remove a member from the base.

The user will lose access to this base but their NocoDB account
is not affected.'''
    await _call_tool('member_remove', {'member_id': member_id, 'confirm': confirm})


@call_tool_app.command(name='attachment_upload')
async def attachment_upload(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
    record_id: Annotated[str, cyclopts.Parameter(help="The record ID to attach the file to")],
    field_id: Annotated[str, cyclopts.Parameter(help="The Attachment field ID (e.g., \"fld_xxx\")")],
    filename: Annotated[str, cyclopts.Parameter(help="The filename for the uploaded file (e.g., \"document.pdf\")")],
    content_base64: Annotated[str, cyclopts.Parameter(help="Base64-encoded file content")],
    content_type: Annotated[str, cyclopts.Parameter(help="MIME type of the file (e.g., \"application/pdf\", \"image/png\")")],
) -> None:
    '''Upload a file attachment to a record\'s Attachment field.

The file content must be provided as base64-encoded data.'''
    await _call_tool('attachment_upload', {'table_id': table_id, 'record_id': record_id, 'field_id': field_id, 'filename': filename, 'content_base64': content_base64, 'content_type': content_type})


@call_tool_app.command(name='storage_upload')
async def storage_upload(
    *,
    filename: Annotated[str, cyclopts.Parameter(help="The filename (e.g., \"logo.png\", \"document.pdf\")")],
    content_base64: Annotated[str, cyclopts.Parameter(help="Base64-encoded file content")],
    content_type: Annotated[str | None, cyclopts.Parameter(help="Optional MIME type (auto-detected if not provided)\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional MIME type (auto-detected if not provided)\"\n                          }")] = None,
) -> None:
    '''Upload a file to NocoDB general storage.

This uploads a file to storage without attaching it to a specific record.
Useful for assets that need to be referenced across multiple records.'''
    # Parse JSON parameters
    content_type_parsed = json.loads(content_type) if isinstance(content_type, str) else content_type

    await _call_tool('storage_upload', {'filename': filename, 'content_base64': content_base64, 'content_type': content_type_parsed})


@call_tool_app.command(name='export_csv')
async def export_csv(
    *,
    view_id: Annotated[str, cyclopts.Parameter(help="The view ID (e.g., \"vw_xxx\")")],
    offset: Annotated[str | None, cyclopts.Parameter(help="Row offset for pagination (skip first N rows)\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"integer\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Row offset for pagination (skip first N rows)\"\n                          }")] = None,
    limit: Annotated[str | None, cyclopts.Parameter(help="Maximum number of rows to export\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"integer\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Maximum number of rows to export\"\n                          }")] = None,
) -> None:
    '''Export a view\'s data as CSV.'''
    # Parse JSON parameters
    offset_parsed = json.loads(offset) if isinstance(offset, str) else offset
    limit_parsed = json.loads(limit) if isinstance(limit, str) else limit

    await _call_tool('export_csv', {'view_id': view_id, 'offset': offset_parsed, 'limit': limit_parsed})


@call_tool_app.command(name='schema_export_table')
async def schema_export_table(
    *,
    table_id: Annotated[str, cyclopts.Parameter(help="The table ID (e.g., \"tbl_xxx\")")],
) -> None:
    '''Export portable schema for a single table.

Returns a clean schema with system fields and internal IDs removed,
suitable for documentation or recreating the table structure.'''
    await _call_tool('schema_export_table', {'table_id': table_id})


@call_tool_app.command(name='schema_export_base')
async def schema_export_base(
) -> None:
    '''Export portable schema for the entire base with all tables.

Returns a clean schema with system fields and internal IDs removed,
suitable for documentation or recreating the base structure.

Returns:
    BaseSchemaResult with title, description, and tables array.
    Each table contains title and fields array.

Example output:
    {
        "title": "My Project",
        "description": "Project database",
        "tables": [
            {
                "title": "Users",
                "fields": [...]
            },
            {
                "title": "Tasks",
                "fields": [...]
            }
        ]
    }'''
    await _call_tool('schema_export_base', {})


@call_tool_app.command(name='list_resources')
async def list_resources(
) -> None:
    '''List all available resources and resource templates.

Returns JSON with resource metadata. Static resources have a
\'uri\' field, while templates have a \'uri_template\' field with
placeholders like {name}.'''
    await _call_tool('list_resources', {})


@call_tool_app.command(name='read_resource')
async def read_resource(
    *,
    uri: Annotated[str, cyclopts.Parameter(help="The URI of the resource to read")],
) -> None:
    '''Read a resource by its URI.

For static resources, provide the exact URI. For templated
resources, provide the URI with template parameters filled in.

Returns the resource content as a string. Binary content is
base64-encoded.'''
    await _call_tool('read_resource', {'uri': uri})


if __name__ == "__main__":
    app()
